[tool.ruff]
line-length = 88
target-version = "py310"
lint.select = ["E", "F", "I"]
lint.ignore = []

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "training/evaluation/tests"
]
python_files = "test_*.py"
