[tool.ruff]
# The Linter Config (Makes your code look standard)
line-length = 88
target-version = "py39"

# E = pycodestyle errors, F = Pyflakes, I = Import sorting
lint.select = ["E", "F", "I"]
lint.ignore = []

[tool.pytest.ini_options]
# The Test Config
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
python_files = "test_*.py"